# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    waist_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    head_group_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    left_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    right_hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    chassis_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - l_j1
      - l_j2
      - l_j3
      - l_j4
      - l_j5
      - l_j6
      - l_j7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - r_j1
      - r_j2
      - r_j3
      - r_j4
      - r_j5
      - r_j6
      - r_j7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
waist_group_controller:
  ros__parameters:
    joints:
      - waist_lift_joint
      - waist_rotate_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
head_group_controller:
  ros__parameters:
    joints:
      - head_left_right_joint
      - head_up_down_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

left_hand_controller:
  ros__parameters:
    joints:
      - left_hand_thumbCMC
      - left_hand_thumbMCP
      - left_hand_indexMCP
      - left_hand_indexPIP
      - left_hand_middleMCP
      - left_hand_middlePIP
      - left_hand_ringMCP
      - left_hand_ringPIP
      - left_hand_littleMCP
      - left_hand_littlePIP
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

right_hand_controller:
  ros__parameters:
    joints:
      - right_hand_thumbCMC
      - right_hand_thumbMCP
      - right_hand_indexMCP
      - right_hand_indexPIP
      - right_hand_middleMCP
      - right_hand_middlePIP
      - right_hand_ringMCP
      - right_hand_ringPIP
      - right_hand_littleMCP
      - right_hand_littlePIP
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

chassis_controller:
  ros__parameters:
    joints:
      - chassis_rotate_joint
      - left_wheel_joint
      - right_wheel_joint
      - driven_wheel_11_joint
      - driven_wheel_12_joint
      - driven_wheel_21_joint
      - driven_wheel_22_joint
      - driven_wheel_31_joint
      - driven_wheel_32_joint
      - driven_wheel_41_joint
      - driven_wheel_42_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
